"""add team id to tasks

Revision ID: 2ad175af713b
Revises: 25db38bd38ed
Create Date: 2026-04-29 20:17:50.720941
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ad175af713b'
down_revision: Union[str, None] = '25db38bd38ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_column('tasks', 'team_id')
    # ### end Alembic commands ###