"""add user email verification fields

Revision ID: b8dc3c7300ec
Revises: e7a1ba50a1d8
Create Date: 2026-05-03 19:28:14.570772
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8dc3c7300ec'
down_revision: Union[str, None] = 'e7a1ba50a1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_otp_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_otp_verified_at')
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###