"""update cascade delete rules

Revision ID: d52f72df7d65
Revises: 2ad175af713b
Create Date: 2026-04-29 22:15:42.495188
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd52f72df7d65'
down_revision: Union[str, None] = '2ad175af713b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_team_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_assignee_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_assignee_id_fkey', 'tasks', 'users', ['assignee_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('tasks_team_id_fkey', 'tasks', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###