"""add integration tables

Revision ID: e7a1ba50a1d8
Revises: d52f72df7d65
Create Date: 2026-04-30 10:08:04.463602
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e7a1ba50a1d8'
down_revision: Union[str, None] = 'd52f72df7d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'account_email', name='uq_integration_user_provider_email')
    )
    op.create_index(op.f('ix_integration_accounts_account_email'), 'integration_accounts', ['account_email'], unique=False)
    op.create_index(op.f('ix_integration_accounts_id'), 'integration_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_integration_accounts_provider'), 'integration_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_accounts_user_id'), 'integration_accounts', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_account_id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('organizer_email', sa.String(length=320), nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_account_id', 'provider_event_id', name='uq_calendar_event_account_event')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_integration_account_id'), 'calendar_events', ['integration_account_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_provider_event_id'), 'calendar_events', ['provider_event_id'], unique=False)
    op.create_table('imported_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_account_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_account_id', 'provider_message_id', name='uq_imported_email_account_message')
    )
    op.create_index(op.f('ix_imported_emails_id'), 'imported_emails', ['id'], unique=False)
    op.create_index(op.f('ix_imported_emails_integration_account_id'), 'imported_emails', ['integration_account_id'], unique=False)
    op.create_index(op.f('ix_imported_emails_provider_message_id'), 'imported_emails', ['provider_message_id'], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=False),
    sa.Column('provider_transcript_id', sa.String(length=255), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcripts_calendar_event_id'), 'meeting_transcripts', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_meeting_transcripts_id'), 'meeting_transcripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_transcripts_id'), table_name='meeting_transcripts')
    op.drop_index(op.f('ix_meeting_transcripts_calendar_event_id'), table_name='meeting_transcripts')
    op.drop_table('meeting_transcripts')
    op.drop_index(op.f('ix_imported_emails_provider_message_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_integration_account_id'), table_name='imported_emails')
    op.drop_index(op.f('ix_imported_emails_id'), table_name='imported_emails')
    op.drop_table('imported_emails')
    op.drop_index(op.f('ix_calendar_events_provider_event_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_integration_account_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_integration_accounts_user_id'), table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_provider'), table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_id'), table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_account_email'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    # ### end Alembic commands ###